Repository ourjapanlife/findadoc-web, pull requests merged in 2023-12, with the labels that each got.

#296 migrated eslint to flat config
  .eslintrc.js
  app-coming-soon.vue
  assets/favicon.ico
  assets/findadoc-social.png
  components/MapContainer.vue
  eslint.config.js
  nuxt.config.js
  package.json
  pages/about.vue
  tsconfig.json
  typedefs/gqlTypes.ts
  typesgeneratorconfig.ts
  yarn.lock
Labels: enhancement

#297 fixing linting
  .github/workflows/lint.yml
  .github/workflows/vitest.yml
  cypress/screenshots/home.cy.ts/Visits the home page -- allows setting search fields (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select English from the language bar (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select Japanese from the language bar (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select select a language (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- shows doctors nearby (failed).png
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: enhancement

#291 Change Filter raw text to i18n string
  components/SearchResultsList.vue
  i18n/locales/en.json
  i18n/locales/ja.json
Labels: i18n, localization

#298 Rebuild website!
  app.vue
  assets/css/tailwind.css
  assets/images/avatars/EmanueleMonica.jpg
  assets/images/avatars/KunikoArita.png
  assets/images/avatars/NiayaHarperIgarashi.jpg
  assets/images/avatars/andrewleemhuis.jpeg
  assets/images/avatars/ayayumino.jpg
  assets/images/avatars/chunyanli.jpeg
  assets/images/avatars/keiyumino.jpg
  assets/images/avatars/shingotoyoda.jpg
  assets/images/doctor_ayayumino.jpg
  assets/images/loading.svg
  components/Footer.vue
  components/Loader.vue
  components/LocaleSelector.vue
  components/MainContentContainer.vue
  components/MapContainer.vue
  components/SearchBar.vue
  components/SearchResultDetails.vue
  components/SearchResultsList.vue
  components/SearchResultsListItem.vue
  components/SubmissionCompleted.vue
  components/SubmissionForm.vue
  components/TopNav.vue
  i18n.options.ts
  i18n/index.ts
  i18n/locales/en.json
  i18n/locales/ja.json
  nuxt.config.js
  package.json
  pages/about.vue
  pages/submit.vue
  stores/loadingStore.ts
  stores/localeStore.ts
  stores/locationStore.ts
  stores/locationsStore.ts
  stores/navigationStore.ts
  stores/searchResultsStore.ts
  stores/specialtiesStore.ts
  stores/submissionStore.ts
  test/stores/navigationStore.spec.ts
  typedefs/gqlTypes.ts
  utils/apollo.ts
  utils/arrayUtils.ts
  utils/gqlTool.ts
  utils/objectUtils.ts
  utils/stringUtils.ts
  utils/typeUtils.ts
  yarn.lock
Labels: enhancement

#304 fixing prod build
  app.vue
Labels: enhancement

#312 Fixed queries and data fetching ui bugs
  components/MapContainer.vue
  components/SearchResultsList.vue
  stores/searchResultsStore.ts
  typedefs/gqlTypes.ts
Labels: enhancement

#313 fixed cached queries not re-running
  stores/searchResultsStore.ts
Labels: enhancement

#316 MVP UI Fixes
  components/SearchBar.vue
  components/TopNav.vue
Labels: enhancement, design

#317 adding gql types
  typedefs/gqlTypes.ts
Labels: enhancement

#332 updating the api url
  utils/apollo.ts
Labels: enhancement

#333 fixed url for generator
  typesgeneratorconfig.ts
Labels: enhancement

#334 Fixed specialties
  components/SearchResultDetails.vue
  components/SearchResultsListItem.vue
  stores/specialtiesStore.ts
  typedefs/gqlTypes.ts
Labels: enhancement, design

#340 Fix SearchResultList component partially hidden
  components/SearchResultsList.vue
Labels: bug

#352 fix: contain root template in one element
  pages/index.vue
Labels: bug
