Repository ourjapanlife/findadoc-web, pull requests merged in 2024-12, with the labels that each got.

#902 feat: implement update existing facility functionality
  assets/icons/trash-can.svg
  assets/icons/undo-icon.svg
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModEditFacilitySection.vue
  components/ModHealthcareProfessionalSearchbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  stores/facilitiesStore.ts
  stores/healthcareProfessionalsStore.ts
  utils/handleServerErrorMessaging.ts
Labels: enhancement, moderation panel

#855 feat: implement section of form to edit existing healthcare professional
  components/ModEditHealthcareProfessionalSection.vue
  components/ModMainContent.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  stores/healthcareProfessionalsStore.ts
  test/cypress/e2e/moderationEditHealthcareProfessional.cy.ts
  test/fake_data/moderation_dashboard/fakeModHealthcareprofessionalData.json
Labels: enhancement

#917 feat: implement delete facility functionality to moderation panel
  components/ModEditFacilityOrProfessionalTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  stores/facilitiesStore.ts
Labels: enhancement, moderation panel

#901 fix(lang): update language dropdown options for search and i18n
  components/SearchBar.vue
  stores/localeStore.ts
Labels: i18n, code quality, localization

#923 fix: implemented changes to display Search bar only on the index page
  components/TopNav.vue
  test/cypress/e2e/about.cy.ts
  test/cypress/e2e/privacy.cy.ts
  test/cypress/e2e/submit.cy.ts
Labels: bug, enhancement, good first issue, design, UI / UX
