Repository ourjapanlife/findadoc-web, pull requests merged in 2024-11, with the labels that each got.

#847 feat: add mutation to delete existing facility
  stores/facilitiesStore.ts
Labels: enhancement

#875 feat: add server response type to frontend
  typedefs/serverResponse.ts
Labels: enhancement

#846 feat: add mutation to delete healthcare professional
  stores/healthcareProfessionalsStore.ts
Labels: enhancement

#879 chore: integrate locale formatting from localeStore for language display
  components/ModEditSubmissionForm.vue
Labels: enhancement

#890 fix: change locales to send code to backend
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
  stores/localeStore.ts
Labels: bug

#883 feat: implement autofill to edit existing facility section
  components/ModEditFacilitySection.vue
  components/ModSubmissionListContainer.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  stores/facilitiesStore.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/fake_data/moderation_dashboard/fakeModFacilityData.json
Labels: enhancement, cypress

#887 fix: improve submission form ui and ux
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
  components/SubmissionCompleted.vue
  components/SubmissionForm.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  pages/submit.vue
  stores/moderationSubmissionsStore.ts
  stores/submissionStore.ts
  test/cypress/e2e/submit.cy.ts
  typedefs/serverResponse.ts
  utils/graphql.ts
  utils/handleServerErrorMessaging.ts
Labels: bug, enhancement

#910 feat(lang): add Tagalog localization
  i18n/index.ts
  i18n/locales/tl.json
  stores/localeStore.ts
Labels: enhancement, i18n, localization

#922 fix: change watch to selected submission Id to avoid unwanted UI updates
  components/ModEditSubmissionForm.vue
Labels: bug, moderation panel
