Repository ourjapanlife/findadoc-web, pull requests merged in 2024-07, with the labels that each got.

#612 feat: show filtered data in ModSubmissionList
  components/ModDashboardLeftNavbar.vue
  components/ModSubmissionListContainer.vue
  cypress/e2e/moderationDashboard.cy.ts
  stores/moderationSubmissionsStore.ts
Labels: moderation panel

#614 feat: implement transition for fade-in images
  components/FadeInTransitionImage.vue
  components/MemberComponent.vue
  cypress/e2e/about.cy.ts
  pages/about.vue
Labels: UI/UX

#613 Chore: upgraded packages
  components/ModSubmissionsEditFormFacility.vue
  components/SearchResultDetails.vue
  components/SearchResultsListItem.vue
  components/SubmissionForm.vue
  eslint.config.js
  nuxt.config.js
  package.json
  yarn.lock
Labels: bug, dependencies

#615 chore: remove stylelint
  .stylelintrc
  README.md
  package.json
  yarn.lock
Labels: dependencies, code quality

#625 refactor: implement new error logic in submission form
  components/SubmissionForm.vue
  cypress/e2e/submit.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  utils/formValidations.ts
Labels: bug

#631 feat: implement pagination for moderation
  components/ModEditSubmissionTopbar.vue
  components/ModLeftNavbar.vue
  components/ModMainContent.vue
  components/ModSubmissionListContainer.vue
  cypress.config.ts
  pages/moderation.vue
  pages/moderation/editsubmission/[id].vue
Labels: enhancement, moderation panel

#635 feat: create composable to check viewport
  pages/index.vue
  utils/useScreenOrientation.ts
Labels: enhancement, UI/UX

#645 feat(lang): add Russian translations
  i18n/index.ts
  i18n/locales/ru.json
  stores/localeStore.ts
Labels: i18n

#646 feat(lang): add German language
  i18n/index.ts
  i18n/locales/de.json
  stores/localeStore.ts
Labels: i18n

#649 FIX(UI): overlapping modal with footer for desktop users
  components/MainContentContainer.vue
Labels: bug, UI/UX

#663 test: improve test speed for ci/cd pipeline
  cypress/e2e/about.cy.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/moderationDashboard.cy.ts
  cypress/e2e/privacy.cy.ts
  cypress/e2e/submit.cy.ts
Labels: CI/CD

#661 fix: add timeout to cypress config for ci timeout
  cypress.config.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/moderationDashboard.cy.ts
  cypress/e2e/submit.cy.ts
Labels: bug

#665 fix: change intercept order to confirm route registration
  cypress/e2e/moderationDashboard.cy.ts
Labels: bug, testing

#671 feat: implement toast plugin for app
  package.json
  plugins/vue-toastification-plugin.ts
  yarn.lock
Labels: enhancement
