Repository ourjapanlife/findadoc-web, pull requests merged in 2024-03, with the labels that each got.

#402 Add healthcare professional degrees to SearchResultDetails
  components/SearchResultDetails.vue
  components/SearchResultsList.vue
  components/SearchResultsListItem.vue
Labels: enhancement

#409 Debug the ESLint config file
  cypress/support/index.d.ts
  eslint.config.js
  i18n.options.ts
  nuxt.config.js
  package.json
  stores/locationsStore.ts
  stores/menuStore.ts
  stores/searchResultsStore.ts
  stores/submissionStore.ts
  tailwind.config.js
  utils/apollo.ts
  utils/objectUtils.ts
  utils/stringUtils.ts
  yarn.lock
Labels: bug, help wanted

#401 Add tests for localeStore
  test/functional/localStore.spec.ts
  vitest.config.ts
Labels: testing

#406 feat: add photos, titles, and names on about us
  app.vue
  assets/images/heart-plus.png
  assets/images/heart-plus.svg
  components/MainContentContainer.vue
  components/MemberComponent.vue
  cypress/e2e/home.cy.ts
  cypress/screenshots/home.cy.ts/Visits the home page -- shows the SearchResultsList (failed).png
  i18n/locales/en.json
  i18n/locales/ja.json
  member_directory/members.json
  pages/about.vue
  svg.d.ts
Labels: enhancement

#418 fix: move avatars to public dir for rendering
  member_directory/members.json
  public/avatars/EmanueleMonica.jpg
  public/avatars/KunikoArita.png
  public/avatars/NiayaHarperIgarashi.jpg
  public/avatars/andrewleemhuis.jpeg
  public/avatars/ayayumino.jpg
  public/avatars/chunyanli.jpeg
  public/avatars/keiyumino.jpg
  public/avatars/lashawntoyoda.jpg
  public/avatars/philipermish.jpg
  public/avatars/russellmiller.jpg
  public/avatars/shingotoyoda.jpg
  typedefs/gqlTypes.ts
Labels: bug

#325 changed from apolloclient to graphql-request
  app.vue
  components/SearchBar.vue
  components/SubmissionForm.vue
  package.json
  stores/locationsStore.ts
  stores/searchResultsStore.ts
  stores/submissionStore.ts
  utils/apollo.ts
  utils/gqlTool.ts
  utils/graphql.ts
  yarn.lock
Labels: enhancement, design

#424 upgraded and tested packages
  package.json
  yarn.lock
Labels: enhancement, dependencies, security

#428 Debug undefined name when name does not exist in locale language.
  components/SearchResultDetails.vue
Labels: bug

#432 style: add margin on bottom
  pages/submit.vue
Labels: enhancement

#429 fix: change image from png to svg
  assets/images/heart-plus.svg
  pages/about.vue
Labels: enhancement

#434 feat: add prettierignore to disable prettier
  .prettierignore
Labels: code quality

#435 chore: remove console logs and alerts
  stores/locationsStore.ts
  stores/menuStore.ts
  stores/searchResultsStore.ts
  stores/submissionStore.ts
Labels: code quality

#430 fix: remove duplicate locations
  components/SearchBar.vue
Labels: enhancement

#438 Change the husky install command.
  package.json
Labels: bug

#439 Update husky file to v9 standard.
  .husky/pre-push
Labels: enhancement
