Repository ourjapanlife/findadoc-web, pull requests merged in 2024-02, with the labels that each got.

#379 Migrate formatting rules for ESlint and StyleLint.
  .stylelintrc
  eslint.config.js
  package.json
  yarn.lock
Labels: code quality

#383 fix: update build and start commands for cypress workflow
  .github/workflows/cypress.yml
Labels: bug, testing

#380 Update Cypress Home Tests
  .yarn/releases/yarn-4.1.0.cjs
  cypress.config.ts
  cypress/e2e/home.cy.ts
  cypress/screenshots/home.cy.ts/Visits the home page -- allows setting search fields (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select English from the language bar (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select Japanese from the language bar (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- can select select a language (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- shows doctors nearby (failed).png
Labels: testing

#393 fix: add test for modal store to fix failing vitest workflow
  test/functional/modalStore.spec.ts
Labels: bug, testing

#350 docs: update PR template to include screenshots
  .github/pull_request_template.md
Labels: documentation

#396 test: add tests for loadingStore
  test/functional/loadingStore.spec.ts
Labels: code quality, testing
