Repository ourjapanlife/findadoc-web, pull requests merged in 2024-05, with the labels that each got.

#464 feat: add page for moderation panel
  nuxt.config.js
  pages/moderation.vue
Labels: moderation panel

#467 Add layout component for moderation panel
  app.vue
  components/ModLeftNavbar.vue
  components/ModMainContent.vue
  components/ModTopbar.vue
  pages/moderation.vue
  stores/moderationScreenStore.ts
Labels: enhancement, MVP, moderation panel

#476 feat: implement main container for submission
  components/ModMainContent.vue
  components/ModSubmissionListContainer.vue
Labels: moderation panel

#473 feat: Implement ModDashboardLeftNavbar with partial functionality.
  assets/images/check-box.svg
  assets/images/disabled-by-default.svg
  assets/images/note-stack-add.svg
  components/ModDashboardLeftNavbar.vue
  components/ModLeftNavbar.vue
Labels: moderation panel

#475 chore: rename local test file to locale
  test/functional/localeStore.spec.ts
Labels: code quality

#485 Several UI experience improvements
  components/BetaBanner.vue
  components/LocaleSelector.vue
  components/MainContentContainer.vue
  components/SearchResultsList.vue
  components/TopNav.vue
  pages/index.vue
  tailwind.config.js
Labels: UI / UX

#489 chore: add home string for JaJp
  i18n/locales/ja.json
Labels: i18n

#490 chore: resize and rename members pics
  member_directory/members.json
  public/avatars/KunikoArita.png
  public/avatars/andrew_leemhuis.jpg
  public/avatars/aya_yumino.jpg
  public/avatars/ayayumino.jpg
  public/avatars/chunyan_li.jpg
  public/avatars/chunyanli.jpeg
  public/avatars/emanuele_monica.jpg
  public/avatars/kei_yumino.jpg
  public/avatars/keiyumino.jpg
  public/avatars/kuniko_arita.jpg
  public/avatars/lashawn_toyoda.jpg
  public/avatars/niaya_harper_igarashi.jpg
  public/avatars/philip_ermish.jpg
  public/avatars/philipermish.jpg
  public/avatars/russell_miller.jpg
  public/avatars/russellmiller.jpg
  public/avatars/shingo_toyoda.jpg
  public/avatars/shingotoyoda.jpg
Labels: code quality

#496 fix: remove duplicate variable key breaking submit page
  stores/submissionStore.ts
Labels: bug

#481 feat: implement list item component with partial functionality
  components/ModSubmissionListContainer.vue
  components/ModSubmissionListItemComponent.vue
Labels: moderation panel

#493 fix: improve responsiveness and component visibility
  app.vue
  components/HamburgerComponent.vue
  components/MainContentContainer.vue
  components/MapContainer.vue
  components/TopNav.vue
  i18n/locales/en.json
  pages/about.vue
  pages/index.vue
  pages/privacypolicy.vue
  pages/submit.vue
  pages/terms.vue
  stores/menuStore.ts
Labels: bug, UI/UX

#505 chore: fix scrolling and page width
  pages/index.vue
  pages/submit.vue
Labels: UI/UX

#494 test: add cypress testing for pages
  components/Footer.vue
  components/HamburgerComponent.vue
  components/MemberComponent.vue
  components/SubmissionForm.vue
  components/TopNav.vue
  cypress/e2e/about.cy.ts
  cypress/e2e/privacy.cy.ts
  cypress/e2e/submit.cy.ts
  cypress/screenshots/home.cy.ts/Visits the home page -- allows setting search fields (failed).png
  cypress/screenshots/home.cy.ts/Visits the home page -- shows the SearchResultsList (failed).png
  cypress/support/commands.js
  cypress/support/index.d.ts
  cypress/tsconfig.json
  package.json
  pages/about.vue
  pages/privacypolicy.vue
  pages/submit.vue
  tsconfig.json
  yarn.lock
Labels: code quality

#512 fix: change the old import to new style
  components/ModDashboardLeftNavbar.vue
Labels: bug, moderation panel
