Repository ourjapanlife/findadoc-web, pull requests merged in 2024-06, with the labels that each got.

#506 feat: create topbar for edit submission form
  app.vue
  assets/icons/checkmark-square.svg
  assets/icons/content-copy.svg
  components/ModEditSubmissionTopbar.vue
  components/ModSubmissionListContainer.vue
  components/ModSubmissionListItemComponent.vue
  components/ModTopbar.vue
  cypress/e2e/moderationDashboard.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
  package.json
  pages/moderation.vue
  stores/moderationScreenStore.ts
  yarn.lock
Labels: moderation panel

#516 refactor: change dynamic code to static
  components/ModDashboardLeftNavbar.vue
  cypress/e2e/moderationDashboard.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
Labels: moderation panel

#465 Create form to edit submissions in moderation panel
  assets/icons/looking-glass.svg
  components/ModInputField.vue
  components/ModMainContent.vue
  components/ModSubmissionsEditFormFacility.vue
  cypress/e2e/moderationDashboard.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
  pages/moderation.vue
  stores/moderationFormInputStore.ts
  utils/formValidations.ts
  utils/stringUtils.ts
Labels: enhancement, help wanted, MVP, moderation panel

#528 fix/show loading leftnav
  components/SearchResultsList.vue
  cypress/e2e/home.cy.ts
Labels: enhancement

#535 fix: update scripts with nuxt env and semicolon
  app.vue
  nuxt.config.js
  package.json
  utils/graphql.ts
Labels: bug

#532 feat: add validation to submission form
  components/SubmissionCompleted.vue
  components/SubmissionForm.vue
  cypress/e2e/submit.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
  utils/formValidations.ts
  utils/stringUtils.ts
Labels: enhancement, code quality

#545 chore: add margin to bottom of submit component
  components/SubmissionForm.vue
Labels: UI/UX

#534 Create healthcare professional search component
  components/ModHealthcareProfessionalSearchbar.vue
  components/ModSubmissionsEditFormFacility.vue
  cypress/e2e/moderationDashboard.cy.ts
  i18n/locales/en.json
  i18n/locales/ja.json
Labels: enhancement, MVP, moderation panel

#568 chore: update all the typescript types file by file
  stores/loadingStore.ts
  stores/localeStore.ts
  stores/locationsStore.ts
  stores/moderationFormInputStore.ts
  stores/moderationScreenStore.ts
  stores/moderationSubmissionsStore.ts
  stores/searchResultsStore.ts
  stores/submissionStore.ts
  typedefs/gqlTypes.ts
Labels: code quality

#567 Change fonts in searchbar
  components/ModHealthcareProfessionalSearchbar.vue
Labels: code quality

#610 feat: implement autofill for counts
  components/ModDashboardLeftNavbar.vue
  cypress/e2e/moderationDashboard.cy.ts
  typedefs/gqlTypes.ts
Labels: moderation panel
