Repository ourjapanlife/findadoc-web, pull requests merged in 2024-09, with the labels that each got.

#739 feat: implement dashboard topbar
  components/ModDashboardLeftNavbar.vue
  components/ModDashboardTopbar.vue
  components/ModTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  stores/moderationSubmissionsStore.ts
Labels: moderation panel, UI / UX

#724 refactor: implement format function in store for locales
  components/SearchResultsListItem.vue
  stores/localeStore.ts
  test/functional/localeStore.spec.ts
Labels: i18n, code quality, testing, localization

#751 feat: create back button submission form modal
  components/ModEditSubmissionForm.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
Labels: enhancement
