Repository ourjapanlife/findadoc-web, pull requests merged in 2024-10, with the labels that each got.

#758 refactor: update button type
  components/ModEditSubmissionTopbar.vue
Labels: code quality

#761 refactor: remove required validation check from mod input
  components/ModInputField.vue
Labels: code quality

#759 fix: improve variable names in submission store
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
  stores/moderationSubmissionsStore.ts
Labels: code quality

#769 feat: implement modal for submission acceptance
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
Labels: enhancement

#775 chore: set max length for comments in code styling rules
  components/ModEditSubmissionForm.vue
  eslint.config.js
  i18n/checkLocaleKeys.js
  utils/handleScroll.ts
  utils/multiSelectWithoutKeyboard.ts
Labels: code quality

#772 feat: add workflow for validating pr titles
  .github/pull_request_template.md
  .github/workflows/lint-pr-title.yml
  README.md
Labels: enhancement

#767 chore: update gqlTypes.ts based on updated backend schema
  typedefs/gqlTypes.ts
Labels: code quality

#811 chore: update imports in `searchResultsStore`
  stores/searchResultsStore.ts
Labels: code quality

#780 fix: register toast plugin on client
  modules/vue-toastification-module.ts
  nuxt.config.js
  plugins/vue-toastification-plugin.client.ts
Labels: bug, code quality

#792 fix: add type imports to types generator
  typedefs/gqlTypes.ts
  typesgeneratorconfig.ts
Labels: bug, code quality

#794 feat: implement weekly gql types update
  .github/workflows/generate-gql-types.yml
Labels: enhancement, code quality, CI/CD

#823 refactor: update bot to only run on minor and security updates
  renovate.json
Labels: code quality

#819 feat: implement approve submission mutation in store
  stores/moderationSubmissionsStore.ts
Labels: enhancement, code quality, testing

#822 test: implement nuxt as vitest environment
  nuxt.config.js
  package.json
  vitest.config.ts
  yarn.lock
Labels: dependencies, testing

#829 feat: add mutation to update existing facility
  stores/facilitiesStore.ts
Labels: enhancement

#718 feat: implement submission acceptance
  assets/icons/trash-can.svg
  components/ModEditSubmissionForm.vue
  cypress/e2e/moderationDashboard.cy.ts
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  stores/moderationSubmissionsStore.ts
Labels: enhancement, moderation panel

#831 feat: add mutation to update healthcare professional
  stores/healthcareProfessionalsStore.ts
Labels: enhancement

#827 feat: implement section of form to edit existing facility
  components/ModEditFacilitySection.vue
  components/ModMainContent.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  stores/facilitiesStore.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/fake_data/moderation_dashboard/fakeModFacilityData.json
Labels: enhancement, testing, UI / UX, pair programming

#853 feat(lang): add french localization
  i18n/index.ts
  i18n/locales/fr.json
  stores/localeStore.ts
Labels: i18n, localization

#867 test: set defaultCommandTimeout to 10000ms for stability
  cypress.config.ts
  test/cypress/e2e/about.cy.ts
  test/cypress/e2e/home.cy.ts
  test/cypress/e2e/moderationDashboard.cy.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/cypress/e2e/submit.cy.ts
Labels: code quality, testing, cypress

#865 feat: implement mod top bar UI for hp and facility
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModMainContent.vue
  components/ModTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  stores/facilitiesStore.ts
  stores/healthcareProfessionalsStore.ts
  stores/moderationSubmissionsStore.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
Labels: enhancement, testing, cypress
