Repository ourjapanlife/findadoc-web, pull requests merged in 2025-09, with the labels that each got.

#1322 refactor: send back partial data when updating a facility in `modEditFacilitySection.vue`
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  stores/facilitiesStore.ts
Labels: enhancement, code quality, moderation panel

#1466 fix: fixed typo in the name of the graphqlHelpers file
  stores/facilitiesStore.ts
  stores/healthcareProfessionalsStore.ts
  stores/moderationSubmissionsStore.ts
  utils/graphqlHelpers.ts
Labels: code quality, moderation panel

#1494 fix: hamburger closes on inside click
  components/HamburgerMenu.vue
Labels: bug

#1486 feat: user drop down menu
  assets/icons/settings-icon.svg
  assets/icons/sign-out-icon.svg
  components/HamburgerMenu.vue
  components/TopNav.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
Labels: enhancement, a11y, UI / UX, nabi-approved

#1502 fix: position toast to top-center
  .gitignore
  plugins/vue-toastification-plugin.client.ts
Labels: bug

#1517 refactor: enable umami analytics through config
  nuxt.config.ts
  plugins/umami.client.js
  typedefs/gqlTypes.ts
Labels: enhancement

#1477 fix: english and japanese prefecture names must match
  components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModCreateFacilitySection.vue
  components/moderation-panel/ModEditFacilitySection.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/facilitiesStore.ts
  stores/locationsStore.ts
  utils/facilitiesUtils.ts
Labels: moderation panel, nabi-approved

#1520 feat: enable tracking of clicked healthcare professional item with umami
  components/SearchResultsList.vue
Labels: enhancement
