Repository ourjapanlife/findadoc-web, pull requests merged in 2025-02, with the labels that each got.

#989 fix: remove skip from clipboard test on the moderation panel
  test/cypress/e2e/moderationDashboard.cy.ts
Labels: testing, moderation panel

#971 fix: nuxt configuration file
  nuxt.config.js
  nuxt.config.ts
  tsconfig.json
Labels: bug, code quality, nuxt

#1003 feat: add lighthouse to workflows
  .github/workflows/lighthouse.yml
Labels: backburner, a11y, CI/CD

#1005 fix: add cypress file to gitignore file
  .gitignore
Labels: bug, cypress

#981 refactor: extract login from Cypress tests
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.ts
  eslint.config.js
  package.json
  test/cypress/e2e/moderationDashboard.cy.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/cypress/e2e/moderationEditHealthcareProfessional.cy.ts
  test/cypress/e2e/moderationEditSubmissionForm.cy.ts
  test/cypress/e2e/moderationEditSubmissionModal.cy.ts
  test/cypress/support/commands.js
  test/cypress/support/commands.ts
  test/cypress/support/e2e.ts
  test/cypress/support/index.d.ts
  test/cypress/tsconfig.json
  test/cypress/utils.ts
  test/fake_data/moderation_dashboard/fakeModHealthcareProfessionalData.json
  yarn.lock
Labels: code quality, testing, cypress

#1011 fix: add ci to e2e testing script
  package.json
Labels: bug, testing

#967 feat: upgrade Nuxt to 3.15.2
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModEditHealthcareProfessionalSection.vue
  components/ModEditSubmissionForm.vue
  declarations.d.ts
  nuxt.config.ts
  package.json
  stores/healthcareProfessionalsStore.ts
  stores/localeStore.ts
  yarn.lock
Labels: bug, i18n, nuxt

#1021 feat: add .env.sample with necessary variables
  .env.sample
Labels: testing, moderation panel

#1012 feat: add loader to ModEdithealthcareProfessionalSection component
  components/ModEditHealthcareProfessionalSection.vue
Labels: enhancement, moderation panel

#1024 chore: add steps to PR template
  .github/pull_request_template.md
Labels: documentation

#1033 fix: update workflow to autogenerate PR with type differences
  .github/workflows/generate-gql-types.yml
Labels: bug, CI/CD

#1045 fix: remove unnecessary `defineProps` import
  components/SearchResultsListItem.vue
Labels: bug, code quality

#952 feat: add lazy load to i18n
  components/LocaleSelector.vue
  i18n.options.ts
  i18n/index.ts
  nuxt.config.ts
Labels: enhancement, i18n, localization

#1025 fix: ESLint config
  eslint.config.js
  package.json
  stores/facilitiesStore.ts
  stores/healthcareProfessionalsStore.ts
  stores/localeStore.ts
  stores/locationsStore.ts
  stores/moderationSubmissionsStore.ts
  stores/searchResultsStore.ts
  utils/stringUtils.ts
  yarn.lock
Labels: code quality, vitest

#1004 feat: implement button on GitHub to update locale files
  .github/workflows/lint-locales-reaction-fix.yml
  .github/workflows/lint-locales.yml
  .gitignore
  .husky/pre-push
  i18n/checkLocaleKeys.js
Labels: enhancement, i18n, CI/CD, research

#1056 feat: improve ux for devs triggering locale workflow
  .github/workflows/lint-locales-reaction-fix.yml
  .github/workflows/lint-locales.yml
Labels: enhancement, UI / UX, CI/CD

#1026 feat: refactor arraysAreEqual utility function to also handle non-primitive variables
  test/vitest/arrayUtils.spec.ts
  utils/arrayUtils.ts
Labels: enhancement, good first issue, testing, pair programming, vitest

#1058 fix: update prop to be optional to remove error
  components/ModDashboardHealthProfessionalCard.vue
Labels: bug, code quality
