Repository ourjapanlife/findadoc-web, pull requests merged in 2025-01, with the labels that each got.

#953 feat: autofill the healthcare professional info in mod
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditFacilitySection.vue
  components/ModEditHealthcareProfessionalSection.vue
  components/ModSubmissionListContainer.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  stores/healthcareProfessionalsStore.ts
  utils/multiSelectWithoutKeyboard.ts
Labels: moderation panel

#958 feat: add Vietnamese localization
  i18n/index.ts
  i18n/locales/vi.json
  stores/localeStore.ts
Labels: localization

#925 feat: add facility search bar component
  .gitignore
  assets/icons/check-mark.svg
  components/ModEditHealthcareProfessionalSection.vue
  components/ModSearchBar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
Labels: enhancement, design, moderation panel, UI / UX

#975 refactor: change modal div to use v-if
  components/ModEditSubmissionForm.vue
  test/cypress/e2e/moderationDashboard.cy.ts
Labels: bug

#974 feat(lang): add italian localization
  i18n/index.ts
  i18n/locales/it.json
  stores/localeStore.ts
Labels: enhancement, good first issue, localization
