Repository ourjapanlife/findadoc-web, pull requests merged in 2025-06, with the labels that each got.

#1215 refactor: centralize Japanese prefecture lists
  components/ModCreateFacilitySection.vue
  components/ModEditFacilitySection.vue
  components/ModEditSubmissionForm.vue
  stores/locationsStore.ts
Labels: code quality, moderation panel, nabi-approved

#1249 fix: doctor website link functionality
  components/SearchResultDetails.vue
  utils/closeOnOutsideClick.ts
Labels: bug, UI / UX, nabi-approved

#1261 fix: fix home test
  test/cypress/e2e/home.cy.ts
Labels: bug, testing, cypress, nabi-approved

#1254 feat: show search suggestions on input focus in ModSearchBar component
  components/ModCreateFacilitySection.vue
  components/ModCreateHealthcareProfessionalSection.vue
  components/ModEditFacilitySection.vue
  components/ModEditHealthcareProfessionalSection.vue
  components/ModEditSubmissionForm.vue
  components/ModSearchBar.vue
Labels: enhancement, moderation panel, UI / UX, nabi-approved

#1251 feat: address in modal opens link in new tab; link styling
  components/SearchResultDetails.vue
Labels: enhancement, UI / UX

#1158 fix: add accessible themes
  assets/css/tailwind.css
  assets/icons/hamburger-menu.svg
  components/HamburgerMenu.vue
  utils/stringUtils.ts
Labels: design, a11y, javascript, nabi-approved

#1271 fix: declare $t to resolve incorrect TypeScript error message for translatable strings
  components/Footer.vue
  components/HamburgerMenu.vue
  components/LoginForm.vue
  components/ModCreateFacilityOrProfessionalTopbar.vue
  components/ModCreateFacilitySection.vue
  components/ModCreateHealthcareProfessionalSection.vue
  components/ModDashboardHealthProfessionalCard.vue
  components/ModDashboardLeftNavbar.vue
  components/ModDashboardTopbar.vue
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModEditFacilitySection.vue
  components/ModEditHealthcareProfessionalSection.vue
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
  components/ModHealthcareProfessionalLeftNavbar.vue
  components/ModHealthcareProfessionalSearchbar.vue
  components/ModSubmissionLeftNavbar.vue
  components/ModSubmissionListContainer.vue
  components/SearchBar.vue
  components/SearchResultDetails.vue
  components/SearchResultsList.vue
  components/SubmissionCompleted.vue
  components/SubmissionForm.vue
  components/TopNav.vue
  pages/about.vue
  pages/moderation.vue
  pages/privacypolicy.vue
Labels: bug, good first issue, code quality, nabi-approved

#1241 fix: avoid race condition `facilitiesStore.ts`
  stores/facilitiesStore.ts
Labels: bug, nabi-approved

#1183 refactor: simplify auth testing environment detection
  .github/workflows/cypress.yml
  cypress.config.ts
  nuxt.config.ts
  package.json
  pages/moderation.vue
  plugins/vue-auth0-plugin.client.ts
  plugins/vue-auth0-plugin.ts
  server/api/test-environment.get.ts
  stores/authStore.ts
  tsconfig.json
  utils/auth0.ts
Labels: bug, testing, CI/CD, cypress

#1286 refactor: move mod components into separate folder
  components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModCreateFacilitySection.vue
  components/moderation-panel/ModCreateHealthcareProfessionalSection.vue
  components/moderation-panel/ModDashboardHealthProfessionalCard.vue
  components/moderation-panel/ModDashboardLeftNavbar.vue
  components/moderation-panel/ModDashboardTopbar.vue
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModEditFacilitySection.vue
  components/moderation-panel/ModEditHealthcareProfessionalSection.vue
  components/moderation-panel/ModEditSubmissionForm.vue
  components/moderation-panel/ModEditSubmissionTopbar.vue
  components/moderation-panel/ModHealthcareProfessionalLeftNavbar.vue
  components/moderation-panel/ModHealthcareProfessionalSearchbar.vue
  components/moderation-panel/ModInputField.vue
  components/moderation-panel/ModLeftNavbar.vue
  components/moderation-panel/ModMainContent.vue
  components/moderation-panel/ModSearchBar.vue
  components/moderation-panel/ModSubmissionLeftNavbar.vue
  components/moderation-panel/ModSubmissionListContainer.vue
  components/moderation-panel/ModTopbar.vue
  nuxt.config.ts
Labels: code quality, nuxt, nabi-approved

#1295 feat: updating loaded to match new branding theme
  assets/icons/loading.svg
Labels: enhancement, UI / UX

#1299 feat: updated specialties available and added top 10
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/specialtiesStore.ts
  test/cypress/e2e/home.cy.ts
  typedefs/gqlTypes.ts
Labels: enhancement, a11y, i18n

#1301 feat: ran yarn generate
  stores/authStore.ts
  stores/specialtiesStore.ts
  test/cypress/e2e/home.cy.ts
  typedefs/gqlTypes.ts
Labels: enhancement

#1307 fix(style): change styling for modal on main page
  components/MainContentContainer.vue
  components/Modal.vue
Labels: design

#1317 refactor: update for new screen sizes
  components/HamburgerMenu.vue
  components/MainContentContainer.vue
  components/Modal.vue
  components/SubmissionForm.vue
  components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModEditSubmissionForm.vue
  components/moderation-panel/ModHealthcareProfessionalLeftNavbar.vue
  composables/closeOnOutsideClick.ts
  composables/handleScroll.ts
  composables/handleServerErrorMessaging.ts
  composables/useScreenOrientation.ts
  pages/index.vue
  utils/useScreenOrientation.ts
Labels: code quality

#1321 refactor: update toast variables
  components/SubmissionForm.vue
  components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModCreateHealthcareProfessionalSection.vue
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModEditFacilitySection.vue
  components/moderation-panel/ModEditHealthcareProfessionalSection.vue
  components/moderation-panel/ModEditSubmissionForm.vue
Labels: code quality, nabi-approved

#1324 fix: prevent `UnsavedChanges` modal from appearing when deleting a facility
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
Labels: enhancement, moderation panel, nabi-approved

#1144 feat: add note as a submission form field and create note input field component
  components/NoteInputField.vue
  components/moderation-panel/ModEditSubmissionForm.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
Labels: enhancement, code quality, moderation panel, pair programming

#1236 feat: add modPagination components
  assets/icons/first-page-pagination.svg
  assets/icons/last-page-pagination.svg
  assets/icons/left-arrow-pagination.svg
  assets/icons/right-arrow-pagination.svg
  components/Pagination.vue
  components/moderation-panel/ModSubmissionListContainer.vue
  i18n/locales/cn.json
  i18n/locales/tl.json
Labels: enhancement, code quality, moderation panel, nabi-approved
