Repository ourjapanlife/findadoc-web, pull requests merged in 2025-03, with the labels that each got.

#973 refactor: update moderation store and ModEditFacilityOrProfessionalTopbar
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModEditFacilitySection.vue
  components/ModHealthcareProfessionalSearchbar.vue
  components/ModTopbar.vue
  stores/moderationScreenStore.ts
Labels: enhancement, code quality

#1047 refactor: remove instances of set and refactor to accept arrays
  components/ModEditHealthcareProfessionalSection.vue
  components/ModSearchBar.vue
  stores/healthcareProfessionalsStore.ts
Labels: enhancement, good first issue, moderation panel, pair programming

#1061 feat: add loading component to modeditfacilitysection
  components/ModEditFacilitySection.vue
Labels: enhancement, moderation panel

#1060 feat: enable pinia store access in cypress
  .github/workflows/cypress.yml
  .gitignore
  global.d.ts
  nuxt.config.ts
  plugins/expose-pinia.client.ts
  test/cypress/e2e/moderationDashboard.cy.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/cypress/e2e/moderationEditSubmissionForm.cy.ts
  test/cypress/tsconfig.json
  test/cypress/utils.ts
Labels: enhancement, code quality, testing, CI/CD, cypress

#1062 fix: enable locale search by all locale display options then save locale code
  components/ModEditHealthcareProfessionalSection.vue
  stores/localeStore.ts
Labels: bug, good first issue, moderation panel

#1089 fix: remove global variable declaration of env for cypress
  cypress.config.ts
Labels: bug, CI/CD

#1081 fix: extend visibility loading component for improved UX
  stores/loadingStore.ts
  test/vitest/loadingStore.spec.ts
Labels: enhancement, moderation panel
