Repository ourjapanlife/findadoc-web, pull requests merged in 2025-08, with the labels that each got.

#1419 refactor: update validation for facilityName English
  test/cypress/e2e/moderationCreateFacility.cy.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  utils/formValidations.ts
  utils/stringUtils.ts
Labels: bug, code quality, nabi-approved

#1257 feat: introduce snapshot testing
  .github/workflows/snapshot-diff.yml
  eslint.config.js
  jest.config.cjs
  layouts/errorLayout.vue
  package.json
  pages/about.vue
  test/jest/snapshot/__snapshots__/about.jest.test.ts.snap
  test/jest/snapshot/about.jest.test.ts
  test/jest/tsconfig.jest.json
  vitest.config.ts
  yarn.lock
Labels: dependencies, testing, pair programming, nabi-approved

#1440 fix: added missing `},` for `modSubmissionListContainer` locale section
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/facilitiesStore.ts
Labels: bug, i18n

#1437 chore: generate types
  typedefs/gqlTypes.ts
Labels: enhancement, i18n, nabi-approved

#1449 feat: use new container item for existing facilities
  assets/icons/hospital-facility-icon.svg
  components/moderation-panel/ModListContainer.vue
  components/moderation-panel/ModListContainerItem.vue
Labels: moderation panel, UI/UX redesign: moderation panel, nabi-approved

#1453 feat(style): change styling of tag for approved
  components/moderation-panel/ModListContainerItem.vue
Labels: UI/UX redesign: moderation panel

#1460 feat: add OD to healthcareProfessional degrees
  typedefs/gqlTypes.ts
Labels: code quality
