Repository ourjapanlife/findadoc-web, pull requests merged in 2025-05, with the labels that each got.

#1121 feat: implement adding existing healthcare professional to facility
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditFacilityOrProfessionalTopbar.vue
  components/ModEditFacilitySection.vue
  components/ModSearchBar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/facilitiesStore.ts
  test/cypress/e2e/moderationEditFacility.cy.ts
  test/fake_data/moderation_dashboard/fakeModFacilityData.json
  test/fake_data/moderation_dashboard/fakeModHealthcareProfessionalData.json
Labels: enhancement, moderation panel, UI / UX

#1130 fix: avoid race condition healthcareProfessionalStore.ts
  stores/healthcareProfessionalsStore.ts
Labels: bug, good first issue

#1177 feat(test): implement tests for ci
  .github/workflows/cypress.yml
  nuxt.config.ts
  package.json
  server/api/auth-token.get.ts
  stores/authStore.ts
Labels: testing, CI/CD, cypress

#1123 feat: add auth to API requests
  .env.sample
  .github/workflows/cypress.yml
  cypress.config.ts
  nuxt.config.ts
  package.json
  server/api/test-environment.get.ts
  stores/authStore.ts
  stores/facilitiesStore.ts
  stores/healthcareProfessionalsStore.ts
  stores/locationsStore.ts
  stores/moderationSubmissionsStore.ts
  stores/searchResultsStore.ts
  stores/submissionStore.ts
  test/cypress/support/commands.ts
  test/cypress/utils.ts
  typedefs/gqlTypes.ts
  typedefs/serverResponse.ts
  utils/graphql.ts
Labels: enhancement, moderation panel

#1182 chore: remove lighthouse action
  .github/workflows/lighthouse.yml
Labels: code quality, CI/CD

#1132 fix: clicking outside modal closes modal
  components/HamburgerMenu.vue
  components/Modal.vue
  utils/closeOnOutsideClick.ts
Labels: bug, good first issue, UI / UX

#1185 fix: fix catch block in loadSecret function
  stores/authStore.ts
Labels: bug

#1124 fix: fix occasional crash from data race condition
  components/SearchBar.vue
Labels: bug, nabi-approved

#1197 fix(style): make moderation dashboard scrollable
  components/ModMainContent.vue
Labels: UI / UX, UI/UX redesign: moderation panel

#1193 chore: update script for test to new e2e headless command
  package.json
Labels: code quality, testing, nabi-approved

#1201 fix: add event default to prevent default action
  utils/closeOnOutsideClick.ts
Labels: bug

#1202 fix: fix ref not being reset to false after submission update
  components/ModEditSubmissionForm.vue
Labels: bug

#1148 feat: add confirmation dialog for unsaved changes on Edit Facility and Edit Professional form
  components/ModEditFacilityOrProfessionalTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/modalStore.ts
Labels: enhancement, moderation panel, UI / UX, nabi-approved

#1204 fix: change which function validates google maps urls
  components/ModEditSubmissionForm.vue
Labels: bug, moderation panel

#1187 feat(test): add tests for healthcareProfessionalsStore
  test/vitest/healthcareProfessionalsStore.spec.ts
Labels: testing, vitest, nabi-approved

#1205 fix(style): display locale of name not spoken languages
  components/ModCreateHealthcareProfessionalSection.vue
  components/ModDashboardHealthProfessionalCard.vue
  components/ModEditHealthcareProfessionalSection.vue
  components/ModEditSubmissionForm.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
Labels: bug, moderation panel, UI/UX redesign: moderation panel, nabi-approved

#1223 feat: implement function to reset facility sections
  stores/facilitiesStore.ts
Labels: enhancement, moderation panel, nabi-approved

#1219 feat: add form validation for name locales
  utils/formValidations.ts
Labels: enhancement, nabi-approved

#1222 feat: implement function to reset healthcare professional section
  stores/healthcareProfessionalsStore.ts
Labels: enhancement, moderation panel, nabi-approved

#1217 fix: favicon missing
  assets/icons/favicon.ico
  nuxt.config.ts
  public/favicon.svg
Labels: bug, nabi-approved

#1139 feat: add functionality for moderator to create a facility
  components/ModCreateFacilityOrProfessionalTopbar.vue
  components/ModCreateFacilitySection.vue
  components/ModDashboardHealthProfessionalCard.vue
  components/ModDashboardTopbar.vue
  components/ModHealthcareProfessionalSearchbar.vue
  components/ModLeftNavbar.vue
  components/ModMainContent.vue
  components/ModTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  pages/moderation/create-facility/index.vue
  stores/facilitiesStore.ts
  stores/moderationScreenStore.ts
  test/cypress/e2e/moderationCreateFacility.cy.ts
Labels: enhancement, moderation panel, UI / UX

#1210 feat: integrate pagination for facilities
  components/ModSubmissionListContainer.vue
Labels: enhancement, code quality, moderation panel

#1233 refactor: change facility section of form for editing submission
  components/ModEditFacilitySection.vue
Labels: enhancement, moderation panel, nabi-approved

#1239 fix: reduce method only runs when submissions are present
  components/ModDashboardLeftNavbar.vue
Labels: bug, code quality, nabi-approved

#1161 fix: cypress handle flaky test, store sync
  test/cypress/e2e/moderationCreateHealthcareProfessional.cy.ts
Labels: bug, testing, moderation panel, cypress, nabi-approved
