Repository ourjapanlife/findadoc-web, pull requests merged in 2025-07, with the labels that each got.

#1344 feat: additional info as hp field in mod panel
  components/NoteInputField.vue
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModEditHealthcareProfessionalSection.vue
  components/moderation-panel/ModEditSubmissionForm.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/healthcareProfessionalsStore.ts
  stores/moderationSubmissionsStore.ts
  typedefs/gqlTypes.ts
  typedefs/tailwindTypes.ts
Labels: enhancement, moderation panel, UI / UX, UI/UX redesign: moderation panel

#1211 refactor: send back partial data when updating a user submission in the `ModEditSubmissionForm.vue`
  components/moderation-panel/ModEditSubmissionForm.vue
  utils/objectUtils.ts
Labels: enhancement, code quality, moderation panel, nabi-approved

#1347 feat: show hp last updated to users
  components/SearchResultDetails.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  utils/dateUtils.ts
Labels: nabi-approved, new feature

#1365 feat: show additional info in SearchResultDetails
  components/SearchResultDetails.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/searchResultsStore.ts
Labels: enhancement, a11y, UI / UX, nabi-approved, new feature

#1345 feat: clean unused keys
  .github/workflows/unused-keys-check.yml
  .gitignore
  i18n/cleanUnusedLocaleKeys.js
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  package.json
Labels: i18n, code quality, CI/CD, pair programming, javascript, nabi-approved

#1370 feat: implement new display for user
  assets/icons/characters-chico-therapy-dog-primary.svg
  components/HamburgerMenu.vue
  components/TopNav.vue
  stores/authStore.ts
Labels: enhancement, design

#1371 fix: add missing last update locale in en.json
  i18n/locales/en.json
Labels: bug, i18n

#1373 feat: add user metadata
  stores/authStore.ts
Labels: UI / UX

#1374 feat: Create a 404 page for users to see #1325.
  assets/icons/characters-chiko-therapy-dog-primary.svg
  error.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  layouts/errorLayout.vue
Labels: enhancement, UI / UX

#1397 chore: add missing deletion translation
  components/moderation-panel/ModEditFacilityOrProfessionalTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
Labels: bug, i18n, nabi-approved

#1398 fix: fix update name to allow for current name locale
  components/moderation-panel/ModCreateHealthcareProfessionalSection.vue
  components/moderation-panel/ModEditHealthcareProfessionalSection.vue
Labels: bug, nabi-approved

#1404 fix: add initalization of optional values to empty strings to fix errors
  stores/facilitiesStore.ts
Labels: bug, nabi-approved

#1401 fix: remove validation for having English name when selected healthcare professional
  components/moderation-panel/ModEditSubmissionForm.vue
Labels: bug, nabi-approved

#1414 refactor: change submission secondary language to optional
  components/SubmissionForm.vue
Labels: UI / UX

#1418 fix: add additional notes to create healthcare with validation fix
  components/moderation-panel/ModCreateFacilityOrProfessionalTopbar.vue
  components/moderation-panel/ModCreateHealthcareProfessionalSection.vue
  stores/healthcareProfessionalsStore.ts
Labels: bug, UI/UX redesign: moderation panel, nabi-approved
