Repository ourjapanlife/findadoc-web, pull requests merged in 2025-04, with the labels that each got.

#1098 fix: fix clrf line endings on windows
  .gitattributes
Labels: bug

#1100 fix: if statements changed to switch for mod active screen
  components/ModMainContent.vue
Labels: enhancement, code quality

#1097 fix: add a doctor page is centered for both firefox and chrome
  components/SubmissionForm.vue
Labels: bug, good first issue

#1107 fix: add the trash can icon back for edit facility
  components/ModDashboardHealthProfessionalCard.vue
Labels: bug, moderation panel

#1102 feat: add leftNavBar for Healthcare Professional
  components/ModEditHealthcareProfessionalSection.vue
  components/ModHealthcareProfessionalLeftNavbar.vue
  components/ModLeftNavbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  stores/moderationScreenStore.ts
  utils/handleScroll.ts
Labels: enhancement, moderation panel

#1096 refactor: change ModEditSubmission to use ModSearchBar
  components/ModEditSubmissionForm.vue
  components/ModEditSubmissionTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  test/cypress/e2e/moderationEditSubmissionForm.cy.ts
  utils/multiSelectWithoutKeyboard.ts
Labels: bug, i18n, code quality, testing, moderation panel, UI / UX

#1110 feat: implement theme switcher in the hamburger menu
  components/HamburgerMenu.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  test/cypress/e2e/home.cy.ts
Labels: enhancement, a11y, code quality, UI / UX

#1072 feat: add functionality for moderator to create healthcare professional
  components/ModCreateFacilityOrProfessionalTopbar.vue
  components/ModCreateHealthcareProfessionalSection.vue
  components/ModDashboardHealthProfessionalCard.vue
  components/ModDashboardTopbar.vue
  components/ModLeftNavbar.vue
  components/ModMainContent.vue
  components/ModSearchBar.vue
  components/ModTopbar.vue
  i18n/locales/cn.json
  i18n/locales/de.json
  i18n/locales/en.json
  i18n/locales/fr.json
  i18n/locales/it.json
  i18n/locales/ja.json
  i18n/locales/pt.json
  i18n/locales/ru.json
  i18n/locales/tl.json
  i18n/locales/vi.json
  pages/moderation/create-healthcare-professional/index.vue
  plugins/expose-pinia.client.ts
  stores/healthcareProfessionalsStore.ts
  stores/moderationScreenStore.ts
  test/cypress/e2e/moderationCreateHealthcareProfessional.cy.ts
  utils/graphql.ts
Labels: enhancement, moderation panel

#1133 refactor: all non-dynamic :to attributes replaced with to attributes
  components/HamburgerMenu.vue
  components/TopNav.vue
  pages/moderation.vue
Labels: good first issue, code quality, nuxt

#1108 fix: mod edit healthcare professional buttons not disabled
  components/ModEditFacilityOrProfessionalTopbar.vue
  stores/healthcareProfessionalsStore.ts
  test/cypress/e2e/moderationEditHealthcareProfessional.cy.ts
Labels: bug

#1135 fix: fixed google maps js error
  components/MapContainer.vue
Labels: bug

#1105 fix: changes to css of the available themes to improve readability
  assets/css/tailwind.css
  components/ModDashboardLeftNavbar.vue
  components/ModSearchBar.vue
  components/ModSubmissionListContainer.vue
Labels: a11y, moderation panel, UI / UX
